### ISSUE TITLE
Any error log?

### ISSUE THREAD

**Issue by kamzealts** [DeachSword/DearSakura#8]
![Screenshot 2024-09-16 at 23 41 36](https://github.com/user-attachments/assets/99dd7dba-13b1-4afd-b5d4-4b50aeed5848)
@WEDeach   File "transfer_bot_2_phone_by_qrcode.py", line 86, in send_key
    qi = self.ins.decryptEncryptedQrIdentifier(qi, self.key, key)
AttributeError: 'CHRLINE' object has no attribute 'decryptEncryptedQrIdentifier'

**Comment by WEDeach** [comment]
NEVER go off topic
